// <auto-generated />
namespace testingproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Two_More_Column_In_Order_Details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Two_More_Column_In_Order_Details));
        
        string IMigrationMetadata.Id
        {
            get { return "202109220721412_add_Two_More_Column_In_Order_Details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
